name: generate-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: SamuelDaza21
          outputs: |
            dist/github-snake.svg?color_snake=%23d4a84b&color_dots=%23d4a84b,%23b39146,%23907030,%236b5520,%234a3a17
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23d4a84b&color_dots=%23d4a84b,%23b39146,%23907030,%236b5520,%234a3a17
            dist/github-snake.gif?color_snake=%23d4a84b&color_dots=%23d4a84b,%23b39146,%23907030,%236b5520,%234a3a17
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "snake: update contribution animation" || echo "No changes"
          git push
